### ISSUE TITLE
DS218Play not supported by MODS GateOne 

### ISSUE THREAD

**Issue by carouselcarousel** [vletroye/SynoPackages#25]
hello,

when I tried to import the package ( MODS_GateOne.spk)  in the package center of the DSM I got an error message:
""This package is not supported on the plaftorm of DiskStation or incopatible with current DSM version."

used DSM: 6.2.3-25426 Update 2

thank you.

**Comment by vletroye** [comment]
Do you see the official package GateOne (available on https://packages.synocommunity.com) in your DSM package center? If you don't, it means your hardware is not supported...


![20200807_105339](https://user-images.githubusercontent.com/9768028/89622842-57566900-d89c-11ea-967e-dc850793cd25.jpg)

**Comment by carouselcarousel** [comment]
Yes I have that in my package center also. But that version is just way out to date from 2017. This is why I tried to look for a new version on your github.

btw that version of GateOne dosn't even work in Chrome, only FF and IE.

**Comment by vletroye** [comment]
The source code of GateOne has not been updated since 2017 indeed: https://github.com/liftoff/GateOne
My Package, if more recent, does however not include any new feature/fix (except that it opens GateOne in a DSM window instead of a new tab).

Could you try this spk : https://www.beatificabytes.be/sspks/packages/MODS_GateOne.spk
If not working, let me know what's your Synology model exactly...

NB.: I never had an issue to run the original GateOne in Chrome. Try to clean your cache, etc..

**Comment by carouselcarousel** [comment]
The MODS GateOne.spk:  
"This package is not supported on the platform of DiskStation or is incompatible with the current DSM version."

DSM version: DSM 6.2.3-25426 Update 2
Model: DS218play

**Comment by vletroye** [comment]
I did update the INFO file to authorize installation on your architecture (RTD1296).

A new SPK is available here: https://www.beatificabytes.be/sspks/packages/MODS_GateOne.spk

Changes are committed in GitHub too.

**Comment by carouselcarousel** [comment]
thank you! works perfectly! 👍
